services:
  postgres:
    image: postgres:16-alpine
    container_name: vavive-gptmaker-postgres
    environment:
      POSTGRES_DB: XXXXX
      POSTGRES_USER: XXXX
      POSTGRES_PASSWORD: XXXXXXX
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vavive -d vavive_gptmaker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
